### ISSUE TITLE
Component Diagram

### ISSUE THREAD

**Issue by sotongjan** [ict2101p2team5/ICT2101-2202-Team-Project#56]

**Comment by sotongjan** [comment]
Come out with the componet diagram that describes the organization and wiring of the physical components in a system.

**Comment by JustBrandonLim** [comment]
Completed initial draft, but still pending more changes before finalization.

**Comment by JustBrandonLim** [comment]
Took over issue from Janice. Reopened issue to include MVC.

**Comment by sotongjan** [comment]
took over the issue
