### ISSUE TITLE
Sequence Diagram (UC1, UC3, UC4)

### ISSUE THREAD

**Issue by JustBrandonLim** [ict2101p2team5/ICT2101-2202-Team-Project#68]

**Comment by JustBrandonLim** [comment]
Must be done in reference to the Class Diagram.

**Comment by bran-donut** [comment]
Provided a diagram illustrating the flow of UC1 - Staff adding availability, UC3 - Staff rejecting job allocation, and UC4 - IT administrator creating manager user
